version: '3.8'
services:
  libtorch_example:
    build: .
    container_name: libtorch_example_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
